### ISSUE TITLE
Email verification link option

### ISSUE THREAD

**Issue by thdoan** [babycourageous/netlify-identity-demo-svelte#20]
Hi, is there a way to configure this project to require the user to click on the email verification link like in [this example](https://github.com/netlify/netlify-identity-widget)?

**Comment by babycourageous** [comment]
Hi @thdoan 

Wow, I thought I had archived this project since it's so outdated.

I'm sure there must be a way, but to be honest I haven't looked at this project in quite a few years. I know Svelte has changed a lot since then and I'm guessing the Netlify API might have as well. 

Sorry I couldn't be more help!

**Comment by babycourageous** [comment]
I'm gonna go ahead and close this - but feel free to comment if you need to add anything!
